// web/angular/src/app/features/agentic-research/components/agentic-research-workspace.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, OnInit, Output, inject } from '@angular/core';
import { DataTableComponent } from '../../../shared/components/data-table.component';
import { DatasetComboboxComponent } from '../../../shared/components/dataset-combobox.component';
import { ChartRendererComponent } from '../../recharts/components/chart-renderer.component';
import { AgenticResearchOrchestrator } from '../orchestrator/agentic-research-orchestrator.service';

@Component({
  selector: 'app-agentic-research-workspace',
  imports: [CommonModule, DatasetComboboxComponent, DataTableComponent, ChartRendererComponent],
  providers: [AgenticResearchOrchestrator],
  template: `
    <div class="stack">
      <details class="details-card" open>
        <summary>ML Algorithms + Sample Prompts</summary>
        <div style="margin-top: .75rem;">
          <p class="strong-red">Results take 1-2min</p>
          <p><strong>Sample Prompts</strong></p>
          <ol>
            <li>Run PCA analysis</li>
            <li>Run NMF Decomposition and PLSR</li>
          </ol>
          @if (model.sklearnTools().length > 0) {
            <div class="algo-groups">
              @for (group of model.toolGroups(); track group.name) {
                <div class="algo-group">
                  <p class="algo-group-title">{{ group.name }}</p>
                  <p class="algo-group-items">{{ group.formatted }}</p>
                </div>
              }
            </div>
          } @else {
            <p>Loading...</p>
          }
        </div>
      </details>

      <details class="details-card">
        <summary>Preprocessing Notes</summary>
        <div class="stack-tight" style="margin-top: .75rem;">
          <p><strong>Categorical Encoding:</strong> Text columns with &lt;= 20 unique values are automatically One-Hot Encoded.</p>
          <p><strong>High Cardinality &amp; IDs:</strong> Text columns with &gt; 20 unique values or ID-like names are dropped.</p>
          <p><strong>Date Parsing:</strong> Dates and timestamps are extracted into Year, Month, and Day numeric features.</p>
          <p><strong>Missing Values:</strong> Missing numeric values are imputed using the column median.</p>
          <p><strong>Feature Scaling:</strong> All features are standardized to zero mean and unit variance.</p>
        </div>
      </details>

      <div class="stack-tight">
        <p class="page-kicker">Dataset</p>
        <app-dataset-combobox
          [options]="model.datasetOptions()"
          [selectedId]="model.selectedDatasetId()"
          (changed)="model.onDatasetChange($event, emitDatasetChange)"
        />
      </div>

      <details class="section-card" open>
        <summary style="cursor: pointer; font-weight: 700;">Charts</summary>
        <div style="margin-top: 1rem;">
          @if (model.isLoading()) {
            <div class="empty-panel">Loading dataset...</div>
          } @else if (model.chartStore.chartSpecs().length > 0) {
            <div class="stack">
              @for (spec of model.chartStore.chartSpecs(); track spec.id) {
                <app-chart-renderer
                  [spec]="spec"
                  [removable]="true"
                  (remove)="model.chartStore.removeChartSpec($event)"
                />
              }
            </div>
          } @else {
            <div class="empty-panel">{{ model.error() ?? 'No analysis chart data available yet.' }}</div>
          }
        </div>
      </details>

      <app-data-table [rows]="model.tableRows()" [columns]="model.tableColumns()" />
    </div>
  `
})
export class AgenticResearchWorkspaceComponent implements OnInit {
  @Output() datasetChange = new EventEmitter<string>();
  readonly model = inject(AgenticResearchOrchestrator);
  readonly emitDatasetChange = (id: string) => this.datasetChange.emit(id);

  ngOnInit(): void {
    void this.model.init(this.emitDatasetChange);
  }
}

// web/vue/src/features/agentic-research/components/AgenticResearchWorkspace.vue
<script setup lang="ts">
import { useAgenticResearchOrchestrator } from "~/features/agentic-research/orchestrator";
import DatasetCombobox from "~/components/General/DatasetCombobox.vue";
import DataTable from "~/components/Datatable/DataTable.vue";
import ChartRenderer from "~/features/recharts/components/ChartRenderer.vue";

const emit = defineEmits<{ "dataset-change": [id: string] }>();

const samplePrompts = ["Run PCA analysis", "Run NMF Decomposition and PLSR"];

const {
  datasetOptions,
  selectedDatasetId,
  tableRows,
  tableColumns,
  sklearnTools,
  chartSpecs,
  isLoading,
  error,
  toolGroups,
  onDatasetChange,
  removeChartSpec,
} = useAgenticResearchOrchestrator({
  baseUrl: "/api/ai",
  onDatasetChange: (id) => emit("dataset-change", id),
});
</script>

<template>
  <div class="flex flex-col gap-6">
    <!-- ML Algorithms + Sample Prompts -->
    <details class="rounded-lg border border-zinc-200 bg-white px-4 py-3 text-black" open>
      <summary class="cursor-pointer text-[12px] font-semibold">
        ML Algorithms + Sample Prompts
      </summary>
      <div class="mt-3 text-[12px]">
        <p class="font-bold text-red-600">Results take 1-2min</p>
        <div class="mt-3">
          <p class="font-bold text-zinc-900">Sample Prompts</p>
          <ol class="mt-2 list-decimal space-y-1 pl-4">
            <li v-for="prompt in samplePrompts" :key="prompt">{{ prompt }}</li>
          </ol>
        </div>
        <div v-if="sklearnTools.length > 0" class="mt-4 flex flex-col gap-2">
          <div v-for="group in toolGroups" :key="group.name">
            <p class="text-[11px] font-semibold uppercase tracking-wide">{{ group.name }}</p>
            <p class="text-[12px]">{{ group.formatted }}</p>
          </div>
        </div>
        <p v-else class="mt-1">Loading...</p>
      </div>
    </details>

    <!-- Preprocessing Notes -->
    <details class="rounded-lg border border-zinc-200 bg-white px-4 py-3 text-[12px] text-zinc-600">
      <summary class="cursor-pointer font-semibold text-zinc-900">
        Preprocessing Notes
      </summary>
      <div class="mt-3 flex flex-col gap-2">
        <p><strong>Categorical Encoding:</strong> Text columns with &le; 20 unique values are automatically One-Hot Encoded.</p>
        <p><strong>High Cardinality &amp; IDs:</strong> Text columns with &gt; 20 unique values or ID-like names are dropped to prevent feature explosion.</p>
        <p><strong>Date Parsing:</strong> Dates and timestamps are extracted into Year, Month, and Day numeric features.</p>
        <p><strong>Missing Values:</strong> Missing numeric values are imputed using the column median to maintain robustness against outliers.</p>
        <p><strong>Feature Scaling:</strong> All features are standardized to zero mean and unit variance (StandardScaler) before analysis. This prevents large-range features from dominating algorithms like PCA.</p>
      </div>
    </details>

    <!-- Dataset -->
    <div class="mt-4">
      <div class="mb-4 flex flex-col gap-2">
        <p class="text-xs font-semibold uppercase tracking-wide text-zinc-500">Dataset</p>
        <DatasetCombobox
          :options="datasetOptions"
          :selected-id="selectedDatasetId"
          @change="onDatasetChange"
        />
      </div>

      <!-- Charts -->
      <details class="rounded-2xl border border-zinc-200 bg-white/60 p-4 shadow-sm backdrop-blur-sm" open>
        <summary class="cursor-pointer text-sm font-semibold text-zinc-900">Charts</summary>
        <div class="mt-4">
          <div v-if="isLoading" class="h-56 animate-pulse rounded-xl bg-zinc-100" />
          <div v-else-if="chartSpecs.length > 0" :class="['flex flex-col gap-4', chartSpecs.length > 2 ? 'max-h-[56rem] overflow-y-auto pr-2' : '']">
            <ChartRenderer
              v-for="spec in chartSpecs"
              :key="spec.id"
              :spec="spec"
              removable
              @remove="removeChartSpec"
            />
          </div>
          <div v-else class="rounded-xl border border-dashed border-zinc-200 bg-zinc-50 px-4 py-6 text-sm text-zinc-500">
            {{ error ?? 'No analysis chart data available yet.' }}
          </div>
        </div>
      </details>
    </div>

    <!-- Data Table -->
    <DataTable :rows="tableRows" :columns="tableColumns" />
  </div>
</template>
