// web/vue/src/features/ai-chat/components/ChatSidebar.vue
<script setup lang="ts">
import { useChatSidebarOrchestrator } from "~/features/ai-chat/orchestrator";

const props = withDefaults(defineProps<{
  mode?: "direct" | "research";
  datasetId?: string | null;
}>(), {
  mode: "direct",
  datasetId: null,
});

const {
  messages,
  inputValue,
  isSending,
  modelOptions,
  selectedModelId,
  screenFeedback,
  messagesEl,
  submit,
  handleHistory,
} = useChatSidebarOrchestrator({
  baseUrl: "/api/ai",
  mode: props.mode,
  getDatasetId: () => props.datasetId,
});
</script>

<template>
  <aside class="flex h-full flex-col border-l border-zinc-200 bg-white">
    <div class="flex items-center justify-between border-b border-zinc-200 px-4 py-3">
      <p class="text-xs font-semibold uppercase tracking-wide text-zinc-500">AI Chat</p>
      <select
        v-if="modelOptions.length > 0"
        v-model="selectedModelId"
        aria-label="Select AI model"
        class="rounded border border-zinc-200 px-2 py-0.5 text-[11px] text-zinc-700"
      >
        <option v-for="m in modelOptions" :key="m.id" :value="m.id">{{ m.label }}</option>
      </select>
    </div>

    <div ref="messagesEl" class="flex-1 overflow-y-auto px-4 py-3">
      <div v-if="messages.length === 0" class="text-xs text-zinc-400">
        Ask a question to get started.
      </div>
      <div v-for="msg in messages" :key="msg.id" class="mb-3">
        <p
          :class="[
            'whitespace-pre-wrap rounded-lg px-3 py-2 text-sm',
            msg.role === 'user'
              ? 'ml-6 bg-zinc-900 text-white'
              : 'mr-6 bg-zinc-100 text-zinc-800',
          ]"
        >
          {{ msg.content }}
        </p>
      </div>
      <div v-if="isSending" class="mb-3 mr-6 flex items-center gap-2 rounded-lg bg-zinc-100 px-3 py-2 text-sm text-zinc-500">
        <svg class="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
        <span>Thinking...</span>
      </div>
    </div>

    <div v-if="screenFeedback" class="border-t border-red-100 bg-red-50 px-4 py-2">
      <p class="text-xs text-red-700">{{ screenFeedback.message }}</p>
    </div>

    <form class="border-t border-zinc-200 px-4 py-3" @submit.prevent="submit">
      <div class="flex items-center gap-2">
        <div class="flex items-center gap-1">
          <button
            type="button"
            disabled
            class="flex h-7 w-7 items-center justify-center rounded-md border border-zinc-200 text-sm text-zinc-400"
            title="Disabled for now"
          >
            +
          </button>
          <span class="text-[10px] text-zinc-400">Disabled for now</span>
        </div>
        <input
          v-model="inputValue"
          type="text"
          placeholder="Ask anything"
          aria-label="Chat input"
          class="flex-1 rounded-md border border-zinc-300 px-3 py-2 text-sm text-zinc-900 placeholder:text-zinc-400 focus:border-zinc-500 focus:outline-none"
          @keydown.up="handleHistory('up')"
          @keydown.down="handleHistory('down')"
        />
        <button
          type="submit"
          :disabled="!inputValue.trim() || isSending"
          class="rounded-md bg-zinc-900 px-3 py-2 text-sm font-medium text-white disabled:bg-zinc-400"
        >
          Send
        </button>
      </div>
    </form>
  </aside>
</template>

// web/angular/src/app/features/ai-chat/components/chat-sidebar.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewChecked, Component, ElementRef, Input, OnChanges, OnInit, SimpleChanges, ViewChild, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ChatSidebarOrchestrator } from '../orchestrator/chat-sidebar-orchestrator.service';

@Component({
  selector: 'app-chat-sidebar',
  imports: [CommonModule, FormsModule],
  providers: [ChatSidebarOrchestrator],
  template: `
    <aside class="chat-sidebar">
      <div class="chat-header">
        <p>AI Chat</p>
        @if (chat.modelOptions().length > 0) {
          <select
            aria-label="Select AI model"
            [ngModel]="chat.selectedModelId()"
            (ngModelChange)="chat.selectedModelId.set($event)"
          >
            @for (model of chat.modelOptions(); track model.id) {
              <option [value]="model.id">{{ model.label }}</option>
            }
          </select>
        }
      </div>

      <div #messagesEl class="chat-messages">
        @if (chat.messages().length === 0) {
          <div class="muted" style="font-size: .75rem;">Ask a question to get started.</div>
        }
        @for (message of chat.messages(); track message.id) {
          <p class="chat-message" [class.user]="message.role === 'user'" [class.assistant]="message.role === 'assistant'">
            {{ message.content }}
          </p>
        }
        @if (chat.isSending()) {
          <p class="chat-message assistant"><span class="thinking-spinner"></span> Thinking...</p>
        }
      </div>

      @if (chat.screenFeedback(); as feedback) {
        <div class="chat-feedback">{{ feedback.message }}</div>
      }

      <form class="chat-form" (submit)="$event.preventDefault(); chat.submit()">
        <div class="chat-form-row">
          <button type="button" class="btn secondary" disabled title="Disabled for now">+</button>
          <input
            class="chat-input"
            type="text"
            placeholder="Ask anything"
            aria-label="Chat input"
            [ngModel]="chat.inputValue()"
            name="chatInput"
            (ngModelChange)="chat.inputValue.set($event)"
            (keydown.arrowUp)="$event.preventDefault(); chat.handleHistory('up')"
            (keydown.arrowDown)="$event.preventDefault(); chat.handleHistory('down')"
          />
          <button type="submit" class="btn primary" [disabled]="!chat.hasInput() || chat.isSending()">Send</button>
        </div>
      </form>
    </aside>
  `
})
export class ChatSidebarComponent implements OnInit, OnChanges, AfterViewChecked {
  @Input() mode: 'direct' | 'research' = 'direct';
  @Input() datasetId: string | null = null;
  @ViewChild('messagesEl') messagesEl?: ElementRef<HTMLElement>;

  readonly chat = inject(ChatSidebarOrchestrator);

  ngOnInit(): void {
    this.syncConfig();
    void this.chat.loadModels();
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.syncConfig();
  }

  ngAfterViewChecked(): void {
    const el = this.messagesEl?.nativeElement;
    if (el) el.scrollTop = el.scrollHeight;
  }

  private syncConfig(): void {
    this.chat.configure({ mode: this.mode, datasetId: this.datasetId, baseUrl: '/api/ai' });
  }
}
